baseURL = "https://KhoiNguyendes23.github.io/Kant_Nguyen_Blog_Persional/"
languageCode = "vi"
title = "Blog Lập Trình Mạng"
theme = "blowfish"

[outputs]
  home = ["HTML","RSS","JSON"]

[pagination]
  pagerSize = 10

[params]
  description = "Blog chia sẻ hành trình học lập trình, Java & mạng – hiện đại, dễ đọc."
  defaultTheme = "auto"
  showReadingTime = true
  enableCopyCode = true
  enableToc = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4